# Generated by Django 2.2.6 on 2019-10-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginal_url', models.URLField()),
                ('short_url', models.CharField(max_length=10)),
                ('clicked', models.PositiveIntegerField()),
            ],
        ),
    ]
